from pathlib import Path
from uuid import uuid4

from pptx import Presentation
from pptx.util import Inches, Pt
from langchain_core.tools import tool


PPT_OUTPUT_DIR = Path("generated/ppt")
PPT_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


@tool
def ppt_tool(title: str, content: str) -> str:
    """
    Generate a professional PowerPoint presentation from a title
    and structured content.
    """

    if not title or not title.strip():
        return "PPT generation failed: title cannot be empty."

    if not content or not content.strip():
        return "PPT generation failed: content cannot be empty."

    try:
        presentation = Presentation()

        presentation.slide_width = Inches(13.333)
        presentation.slide_height = Inches(7.5)

        slides_content = [
            section.strip()
            for section in content.split("\n\n")
            if section.strip()
        ]

        title_slide = presentation.slides.add_slide(
            presentation.slide_layouts[0]
        )

        title_slide.shapes.title.text = title.strip()

        if len(title_slide.placeholders) > 1:
            subtitle = title_slide.placeholders[1]
            subtitle.text = "Generated by AgentForge AI"

        for section in slides_content:
            lines = [
                line.strip()
                for line in section.splitlines()
                if line.strip()
            ]

            if not lines:
                continue

            slide = presentation.slides.add_slide(
                presentation.slide_layouts[1]
            )

            slide_title = lines[0]
            slide.shapes.title.text = slide_title

            body = slide.placeholders[1].text_frame
            body.clear()

            for index, line in enumerate(lines[1:]):
                if index == 0:
                    paragraph = body.paragraphs[0]
                else:
                    paragraph = body.add_paragraph()

                paragraph.text = line
                paragraph.level = 0
                paragraph.font.size = Pt(20)

        file_name = f"{uuid4().hex}.pptx"
        output_path = PPT_OUTPUT_DIR / file_name

        presentation.save(output_path)

        return (
            "PowerPoint presentation generated successfully.\n"
            f"File: {output_path.resolve()}\n"
            f"Slides: {len(presentation.slides)}"
        )

    except Exception as exc:
        return f"PPT generation error: {str(exc)}"

    